'''

ALL YOUR CONFIGURATIONS , API KEY AND CREDENTIALS 
UPDATE AS PER REQUIREMENTS

'''


GROQ_API_KEY = ''

MAILGUN_API_KEY = ''
MAILGUN_DOMAIN = ''

# Mailgun API URL
MAILGUN_API_URL = f"https://api.mailgun.net/v3/{MAILGUN_DOMAIN}/messages"